import { Link } from 'react-router-dom'
import PageHeader from '../components/PageHeader'
import { FileText, Scale, AlertTriangle } from 'lucide-react'

export default function Terms() {
  return (
    <div className="max-w-4xl mx-auto p-6 md:p-8">
      <PageHeader eyebrow="Legal" title="Terms of Service" description="Rules and guidelines for using Modulate." />

      <div className="prose-quiet space-y-8">
        <section>
          <h2 className="h-display text-2xl mt-6 mb-3">Acceptance of Terms</h2>
          <p className="text-[color:var(--color-ink-2)] leading-relaxed">
            By accessing or using Modulate, you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the service. These terms apply to all visitors, users, and anyone accessing the platform through any means.
          </p>
        </section>

        <section>
          <h2 className="h-display text-2xl mt-6 mb-3">Account Terms</h2>
          <p className="text-[color:var(--color-ink-2)] leading-relaxed">
            You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must be at least 16 years old to use Modulate. You agree to provide accurate, current, and complete information when creating an account and to keep that information up to date.
          </p>
        </section>

        <section>
          <h2 className="h-display text-2xl mt-6 mb-3">Content You Create</h2>
          <p className="text-[color:var(--color-ink-2)] leading-relaxed">
            You retain ownership of all content you upload, create, or publish through Modulate. Our service does not claim any ownership rights over your content. By using our platform, you grant us a limited, non-exclusive license to process, store, and display your content solely to provide and improve our services.
          </p>
        </section>

        <section>
          <h2 className="h-display text-2xl mt-6 mb-3">Social Media Platform Terms</h2>
          <p className="text-[color:var(--color-ink-2)] leading-relaxed">
            When connecting social media accounts, you agree to comply with the terms of service of each respective platform (YouTube, TikTok, Instagram, Facebook). You are responsible for ensuring you have the necessary permissions and rights to access and use content from those platforms. Modulate does not endorse or assume responsibility for violations of third-party platform terms.
          </p>
        </section>

        <section>
          <h2 className="h-display text-2xl mt-6 mb-3">Prohibited Activities</h2>
          <p className="text-[color:var(--color-ink-2)] leading-relaxed">
            You agree not to use Modulate to:
          </p>
          <ul className="mt-3 list-disc pl-6 space-y-1 text-[color:var(--color-ink-2)]">
            <li>Violate any applicable local, state, national, or international law</li>
            <li>Upload, publish, or distribute harmful, illegal, or infringing content</li>
            <li>Access or attempt to access unauthorized data, accounts, or systems</li>
            <li>Interfere with or disrupt the service or servers connected to the platform</li>
            <li>Use automated means to scrape data or exceed rate limits</li>
            <li>Impersonate another person or entity</li>
            <li>Use the service for spam, phishing, or other deceptive practices</li>
          </ul>
        </section>

        <section>
          <h2 className="h-display text-2xl mt-6 mb-3">Third-Party Services</h2>
          <p className="text-[color:var(--color-ink-2)] leading-relaxed">
            Modulate relies on third-party services including Supabase (for authentication and data storage), social media APIs, and AI providers for content generation. These services have their own terms and privacy policies. We are not responsible for the actions, policies, or availability of third-party services.
          </p>
        </section>

        <section>
          <h2 className="h-display text-2xl mt-6 mb-3">AI-Generated Content</h2>
          <p className="text-[color:var(--color-ink-2)] leading-relaxed">
            Content generated by AI features within Modulate is provided "as is" without warranty. You acknowledge that AI-generated content may contain errors or inaccuracies and that you are solely responsible for reviewing and approving any content before publishing it to social media platforms.
          </p>
        </section>

        <section>
          <h2 className="h-display text-2xl mt-6 mb-3">Disclaimer of Warranties</h2>
          <p className="text-[color:var(--color-ink-2)] leading-relaxed">
            The service is provided on an "as is" and "as available" basis. We do not guarantee that the service will be uninterrupted, timely, secure, or error-free. We disclaim all warranties, express or implied, including warranties of merchantability and fitness for a particular purpose.
          </p>
        </section>

        <section>
          <h2 className="h-display text-2xl mt-6 mb-3">Limitation of Liability</h2>
          <p className="text-[color:var(--color-ink-2)] leading-relaxed">
            To the maximum extent permitted by law, Modulate and its providers shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or use, arising out of or in connection with these Terms or the use of the service.
          </p>
          <div className="mt-4 flex items-start gap-3 text-[color:var(--color-ink-2)]">
            <AlertTriangle size={16} className="mt-0.5 text-[color:var(--color-accent)] shrink-0" />
            <p className="text-sm">This disclaimer applies to all uses of the service, including automated publishing workflows.</p>
          </div>
        </section>

        <section>
          <h2 className="h-display text-2xl mt-6 mb-3">Termination</h2>
          <p className="text-[color:var(--color-ink-2)] leading-relaxed">
            We may terminate or suspend your account at any time, with or without cause and with or without notice, for conduct that violates these Terms or infringes the rights of others. Upon termination, all rights to your account and content cease immediately.
          </p>
        </section>

        <section>
          <h2 className="h-display text-2xl mt-6 mb-3">Governing Law</h2>
          <p className="text-[color:var(--color-ink-2)] leading-relaxed">
            These Terms shall be governed by and construed in accordance with the laws applicable in the jurisdiction where Modulate operates, without regard to its conflict of law provisions. Any disputes shall be resolved through binding arbitration in accordance with the rules of the relevant arbitration body.
          </p>
        </section>

        <section>
          <h2 className="h-display text-2xl mt-6 mb-3">Changes to These Terms</h2>
          <p className="text-[color:var(--color-ink-2)] leading-relaxed">
            We may modify these Terms at any time. Material changes will be communicated via email or a prominent notice on the platform. Continued use of the service after changes constitutes acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="h-display text-2xl mt-6 mb-3">Contact</h2>
          <p className="text-[color:var(--color-ink-2)] leading-relaxed">
            For questions about these Terms of Service, please contact us at <a className="link" href="mailto:support@modulate.so">support@modulate.so</a>.
          </p>
        </section>
      </div>

      <div className="mt-12 pt-6 border-t border-[color:var(--color-border)]">
        <Link to="/" className="btn btn-outline">← Back to home</Link>
      </div>
    </div>
  )
}
